# Generated by Django 5.2.2 on 2025-06-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Review_text',
            new_name='review_text',
        ),
    ]
