# Generated by Django 5.2.2 on 2025-06-25 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_slug'),
        ('theaters', '0002_alter_theater_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('row_label', models.CharField(max_length=1)),
                ('seat_type', models.CharField(max_length=100)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.theater')),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.DateField()),
                ('silver_seats_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gold_seats_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('platinum_seats_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theaters.theater')),
            ],
        ),
    ]
