# Generated by Django 5.2.2 on 2025-06-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0003_seat_showtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='showtime',
            field=models.DateTimeField(),
        ),
    ]
