# Generated by Django 5.2.2 on 2025-06-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Cast',
        ),
    ]
